// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqEXdD3528vXqm7UmOSr1URKX7hqmZTDI',
    appId: '1:489785669570:web:d098a76f4dea2829c0c85b',
    messagingSenderId: '489785669570',
    projectId: 'furniture-app-52ef4',
    authDomain: 'furniture-app-52ef4.firebaseapp.com',
    storageBucket: 'furniture-app-52ef4.appspot.com',
    measurementId: 'G-0TDKS5RTHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPo1nh6-23JujySM2n_zSeYJkdxZHzRRE',
    appId: '1:489785669570:android:b9778aefc78fbb99c0c85b',
    messagingSenderId: '489785669570',
    projectId: 'furniture-app-52ef4',
    storageBucket: 'furniture-app-52ef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc7190vct74iTvCMwssddia_juJ6eioLo',
    appId: '1:489785669570:ios:4afb22dab563ae21c0c85b',
    messagingSenderId: '489785669570',
    projectId: 'furniture-app-52ef4',
    storageBucket: 'furniture-app-52ef4.appspot.com',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc7190vct74iTvCMwssddia_juJ6eioLo',
    appId: '1:489785669570:ios:4afb22dab563ae21c0c85b',
    messagingSenderId: '489785669570',
    projectId: 'furniture-app-52ef4',
    storageBucket: 'furniture-app-52ef4.appspot.com',
    iosBundleId: 'com.example.furnitureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqEXdD3528vXqm7UmOSr1URKX7hqmZTDI',
    appId: '1:489785669570:web:309dc8b9516014cfc0c85b',
    messagingSenderId: '489785669570',
    projectId: 'furniture-app-52ef4',
    authDomain: 'furniture-app-52ef4.firebaseapp.com',
    storageBucket: 'furniture-app-52ef4.appspot.com',
    measurementId: 'G-BTBWX0T32T',
  );
}
